server:
  port: 9080

security:
  basic:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  threadpool:
    default:
      coreSize: 8
      maximumSize: 8
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000